version: "3.9"
services:
  app:
    image: customer-service-app
    ports:
      - 8888:8888
    command: php -S 0.0.0.0:8888
    volumes:
      - ./frontend/db:/app/db
  develop:
    build:
      context: .
      dockerfile: Dockerfile
      target: develop
    ports:
      - 8888:8888
    command: php -S 0.0.0.0:8888 -t frontend
    volumes:
      - ./:/app/
